main: main.cpp Person.o Book.o Serializer.o
	g++ main.cpp Person.o Book.o Serializer.o -o main
Person.o: Person.cpp
	g++ -c Person.cpp
Book.o: Book.cpp
	g++ -c Book.cpp
Serializer.o: Serializer.cpp
	g++ -c Serializer.cpp
